apiVersion: v1
kind: PersistentVolume
metadata:  # PV建立不要加名称空间，因为PV属于集群级别的
  name: mysql-pv  # PV名称
  labels: # 这些labels可以不定义
    name: mysql-pv
    storetype: nfs
    pv: mysql
spec:  # 这里的spec和volumes里面的一样
  storageClassName: default
  accessModes:  # 设置访问模型
    - ReadWriteOnce
  capacity: # 设置存储空间大小
    storage: 600Mi
  persistentVolumeReclaimPolicy: Retain # 回收策略
  nfs:
    path: /home/nfs/data
    server: 192.168.56.108

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  #name: nfs-pvc001
  name: mysql-pvc
  namespace: default
  labels: # 这些labels可以不定义
    name: mysql-pvc
    storetype: nfs
    capacity: 500Mi
spec:
  storageClassName: default
  accessModes:  # PVC也需要定义访问模式，不过它的模式一定是和现有PV相同或者是它的子集，否则匹配不到PV
  - ReadWriteOnce
  resources: # 定义资源要求PV满足这个PVC的要求才会被匹配到
    requests:
      storage: 500Mi  # 定义要求有多大空间
  selector:
    matchLabels:
        pv: mysql

